#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Central parameters for refactor-stage code.

All new parameters introduced during the refactor should live here.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ENV_SH = PROJECT_ROOT / "env.sh"
DEFAULT_MPLCONFIGDIR = "/tmp/matplotlib"

# Trajectory CSV format.
TRAJECTORY_DOF = 7
TRAJECTORY_TIME_COLUMN = "t"
TRAJECTORY_Q_PREFIX = "q"
TRAJECTORY_DQ_PREFIX = "dq"
TRAJECTORY_DDQ_PREFIX = "ddq"
TRAJECTORY_JERK_PREFIX = "jerk"
TRAJECTORY_CANONICAL_COLUMNS = (
    [TRAJECTORY_TIME_COLUMN]
    + [f"{TRAJECTORY_Q_PREFIX}{j}" for j in range(TRAJECTORY_DOF)]
    + [f"{TRAJECTORY_DQ_PREFIX}{j}" for j in range(TRAJECTORY_DOF)]
    + [f"{TRAJECTORY_DDQ_PREFIX}{j}" for j in range(TRAJECTORY_DOF)]
)

Q_LIMITS_7 = np.array([
    [-2.897,  2.897],
    [-1.762,  1.762],
    [-2.897,  2.897],
    [-3.071, -0.070],
    [-2.897,  2.897],
    [-0.017,  3.752],
    [-2.897,  2.897],
], dtype=float)
QDOT_LIMITS_7 = np.array([2.1750, 2.1750, 2.1750, 2.1750, 2.6100, 2.6100, 2.6100], dtype=float)
QDDOT_LIMITS_7 = np.array([15.0, 7.5, 10.0, 12.5, 15.0, 20.0, 20.0], dtype=float)
JERK_SCALE = 0.5
JERK_LIMITS_7 = np.array([
    JERK_SCALE * 750.0,
    JERK_SCALE * 375.0,
    JERK_SCALE * 500.0,
    JERK_SCALE * 625.0,
    JERK_SCALE * 750.0,
    JERK_SCALE * 1000.0,
    JERK_SCALE * 1000.0,
], dtype=float)

# Default arm reset/trajectory start pose.
DEFAULT_INIT_ARM = np.array([0.0, -1.57, 0.0, -0.1, 0.0, 3.14, 0.78], dtype=float)

# Default file paths used by refactor utilities.
DEFAULT_TRAJECTORY_CSV = PROJECT_ROOT / "trajectory.csv"
DEFAULT_AFTERPROCESS_MODE = "simulation"
DEFAULT_AFTERPROCESS_OUTPUT_CSV = PROJECT_ROOT / "refractor" / "trajectory_afterprocess_output.csv"
DEFAULT_AFTERPROCESS_PLOT = True
DEFAULT_AFTERPROCESS_PLOT_DIR = PROJECT_ROOT / "refractor" / "joint_plots"
DEFAULT_VALIDATION_EPS = 1e-12
DEFAULT_AFTERPROCESS_TIME_SCALE = 1.0
DEFAULT_JERK_CONTROL_DT = 0.001
DEFAULT_JERK_CONTROL_OUTPUT_CSV = PROJECT_ROOT / "refractor" / "jerk_limited_trajectory.csv"
DEFAULT_PHASE_SIDECAR_SUFFIX = ".phases.json"

# Soft-throw planning defaults. This refactor path accepts a release
# world position and velocity directly; it does not compute tube windows.
DEFAULT_SOFT_THROW_RELEASE = np.array([0.4, 0.0, 0.9], dtype=float)
DEFAULT_SOFT_THROW_RELEASE_VELOCITY = np.array([1.2, 0.0, -1.2], dtype=float)
DEFAULT_SOFT_THROW_OUTPUT_CSV = DEFAULT_TRAJECTORY_CSV
DEFAULT_SOFT_THROW_PHASES_JSON = Path(str(DEFAULT_SOFT_THROW_OUTPUT_CSV) + DEFAULT_PHASE_SIDECAR_SUFFIX)
DEFAULT_SOFT_THROW_CONTROL_DT = 0.01
DEFAULT_SOFT_THROW_WAYPOINT_DENSITY = 10
DEFAULT_SOFT_THROW_PATH_PLAN_WAYPOINTS = 2
DEFAULT_SOFT_THROW_LIMIT_SCALE = 0.70
DEFAULT_SOFT_THROW_QDDOT_SCALE = 0.60
DEFAULT_SOFT_THROW_MAX_PRE_DURATION_SEC = 5.0
DEFAULT_SOFT_THROW_MAX_DURATION_SEC = 8.0
DEFAULT_SOFT_THROW_IK_MAX_ITER = 50
DEFAULT_SOFT_THROW_IK_KP_POS = 2.0
DEFAULT_SOFT_THROW_IK_KP_ROT = 1.0
DEFAULT_SOFT_THROW_SEGMENT_METHOD = "scurve"
DEFAULT_SOFT_THROW_AUTO_START = False
DEFAULT_SOFT_THROW_DECEL_JOINT_INDEX = 5
DEFAULT_SOFT_THROW_DECEL_J6_BACKOFF_RAD = 0.5
DEFAULT_SOFT_THROW_USE_RELEASE_SELECTOR = True
DEFAULT_SOFT_THROW_TARGET_FRAME = "panda_link7"
DEFAULT_SOFT_THROW_POLY5_CHECK_MAX_SAMPLES = 2000
DEFAULT_SOFT_THROW_JOINT_LIMIT_MARGIN = 0.0
DEFAULT_SOFT_THROW_Q_LIMIT_MARGIN_ABS = 0.005

# Ballistic release candidate defaults. These generate possible ball/lacrosse
# release states from a desired landing point, assuming ball and lacrosse head
# have the same position and velocity at release.
DEFAULT_RELEASE_LANDING_POS = np.array([1.5, 0.0, 0.0], dtype=float)
DEFAULT_RELEASE_INITIAL_POS = np.array([0.7369011564, 0.0020241521, 0.6652749860], dtype=float)
DEFAULT_RELEASE_CANDIDATE_COUNT = 256
DEFAULT_RELEASE_PATH_SAMPLE_COUNT = 80
DEFAULT_RELEASE_GRAVITY = 9.81
DEFAULT_RELEASE_DISTANCE_RANGE = (0.20, 0.90)
DEFAULT_RELEASE_HEIGHT_OFFSET_RANGE = (0.45, 1.00)
DEFAULT_RELEASE_FLIGHT_TIME_RANGE = (0.35, 0.90)
DEFAULT_RELEASE_MAX_SPEED = 2.0
DEFAULT_RELEASE_MIN_HEIGHT = 0.05
DEFAULT_RELEASE_MAX_HEIGHT = 1.40
DEFAULT_RELEASE_SELECTION = "middle"
DEFAULT_RELEASE_PLOT = True
DEFAULT_RELEASE_PLOT_PATH = PROJECT_ROOT / "refractor" / "release_candidates_plot.png"
DEFAULT_RELEASE_PLOT_MAX_PATHS = 64
DEFAULT_RELEASE_PLOT_FIGSIZE = (9, 7)
DEFAULT_RELEASE_PLOT_DPI = 160
DEFAULT_RELEASE_PLOT_SPEED_CMAP = "viridis"
DEFAULT_RELEASE_PLOT_PATH_LINEWIDTH = 0.9
DEFAULT_RELEASE_PLOT_PATH_ALPHA = 0.42
DEFAULT_RELEASE_PLOT_CANDIDATE_SIZE = 18
DEFAULT_RELEASE_PLOT_CANDIDATE_ALPHA = 0.55
DEFAULT_RELEASE_PLOT_SELECTED_SIZE = 80
DEFAULT_RELEASE_PLOT_LANDING_SIZE = 90
DEFAULT_RELEASE_PLOT_INITIAL_SIZE = 70
DEFAULT_RELEASE_PLOT_ARROW_LENGTH = 0.25
DEFAULT_RELEASE_PLOT_RADIUS_SCALE = 0.55
DEFAULT_RELEASE_PLOT_MIN_RADIUS = 0.1
DEFAULT_RELEASE_PLOT_VIEW_ELEV = 23
DEFAULT_RELEASE_PLOT_VIEW_AZIM = -65
DEFAULT_RELEASE_SELECTOR_FRAME = "panda_link7"
DEFAULT_RELEASE_SELECTOR_OBJECT_OFFSET_MODE = "local_from_initial"  # {"world","local","local_from_initial","none"}
DEFAULT_RELEASE_SELECTOR_OBJECT_OFFSET = None
DEFAULT_RELEASE_REFERENCE_Q = np.array([0.0, 0, 0.0, -1.57, 0.0, 3.14, 0.0], dtype=float)
DEFAULT_RELEASE_SELECTOR_POS_TOL = 0.10
DEFAULT_RELEASE_SELECTOR_VEL_TOL = 0.35
DEFAULT_RELEASE_SELECTOR_Q_WEIGHT = 1.0
DEFAULT_RELEASE_SELECTOR_POS_WEIGHT = 20.0
DEFAULT_RELEASE_SELECTOR_VEL_WEIGHT = 2.0
DEFAULT_RELEASE_SELECTOR_IK_MAX_ITER = 200
DEFAULT_RELEASE_SELECTOR_DLS_LAMBDA = 0.05
DEFAULT_RELEASE_SELECTOR_REQUIRE_DECEL_FEASIBLE = True
DEFAULT_RELEASE_SELECTOR_DECEL_MARGIN = 1e-4
DEFAULT_RELEASE_SELECTOR_USE_REACHABLE = False
DEFAULT_PIN_ARM_JOINT_NAME_FORMAT = "panda_joint{}"

# Simulation playback defaults.
DEFAULT_SIM_HEADLESS = False
DEFAULT_SIM_OPEN_ENVIRONMENT_HEADLESS = False
DEFAULT_SIM_PHYSICS_SCENE_PATH = "/World/physicsScene"
DEFAULT_SIM_SPAWN_GROUND = True
DEFAULT_SIM_GROUND_COLOR = (0.42, 0.52, 0.45)
DEFAULT_SIM_ASSET_Z_OFFSET = 0.05
DEFAULT_SIM_WARMUP_STEPS = 120
DEFAULT_SIM_RESET_SETTLE_SEC = 2.0
DEFAULT_SIM_RESET_MIN_SETTLE_SEC = 0.25
DEFAULT_SIM_RESET_STABLE_POS_EPS = 1e-4
DEFAULT_SIM_RESET_STABLE_STEPS = 10
DEFAULT_SIM_WAIT_BEFORE_BALL_RESET_SEC = 1.0
DEFAULT_SIM_HOLD_AFTER_SEC = 1.0
DEFAULT_SIM_BALL_PRIM = "/World/LMM/Ball"
DEFAULT_SIM_HEAD_PRIM = "/World/LMM/Franka/lacrosse"
DEFAULT_SIM_BALL_OFFSET = 0.10
# Set to 1000.0 to execute a 1 ms CSV command stream exactly one physics step at a time.
# Lower values run faster in Isaac Sim but collapse multiple CSV commands into one physics step.
DEFAULT_SIM_PLAYBACK_PHYSICS_HZ = 1000.0
DEFAULT_SIM_PLAYBACK_REALTIME_FACTOR = 0.0  # 0 disables wall-clock throttling; playback follows simulation time.
DEFAULT_SIM_FREQUENCY_MEASURE_STEPS = 240
DEFAULT_SIM_IDLE_SLEEP_SEC = 0.01
DEFAULT_SIM_USE_FIXED_TIME_STEPPING_SETTING = "/app/player/useFixedTimeStepping"
DEFAULT_SIM_COMPENSATE_PLAY_DELAY_SETTING = "/app/player/CompensatePlayDelayInSecs"
DEFAULT_SIM_COMPENSATE_PLAY_DELAY_SEC = 0.0
DEFAULT_SIM_TIMELINE_TICKS_PER_FRAME = 1
DEFAULT_LACROSSE_COLLIDER_ENABLED = False
DEFAULT_LACROSSE_COLLIDER_PRIM = "/World/LMM/Franka/lacrosse/RuntimeSdfCollider"
DEFAULT_LACROSSE_COLLIDER_APPROXIMATION = "sdf"
DEFAULT_LACROSSE_COLLIDER_SDF_RESOLUTION = 256
DEFAULT_LACROSSE_COLLIDER_HIDE_VISUAL = True
DEFAULT_USD_ANALYZE_KEYWORD = "lacrosse"
DEFAULT_RELATIVE_LINK7_NAME = "panda_link7"
DEFAULT_RELATIVE_HEAD_NAME = "LacrossTrophyHead"
DEFAULT_RELATIVE_CHILD_SNAPSHOT_COUNT = 80

# Trajectory plot defaults.
DEFAULT_TRAJECTORY_PLOT_FIGSIZE = (9, 9)
DEFAULT_TRAJECTORY_PLOT_DPI = 150
DEFAULT_TRAJECTORY_PLOT_POINT_SIZE = 6
DEFAULT_TRAJECTORY_PLOT_LIMIT_COLOR = "r"
DEFAULT_TRAJECTORY_PLOT_LIMIT_LINESTYLE = "--"
DEFAULT_TRAJECTORY_PLOT_LIMIT_LINEWIDTH = 1
DEFAULT_TRAJECTORY_PLOT_MARKER_COLOR = "k"
DEFAULT_TRAJECTORY_PLOT_MARKER_LINESTYLE = ":"
DEFAULT_TRAJECTORY_PLOT_MARKER_LINEWIDTH = 1
DEFAULT_TRAJECTORY_PLOT_STAGE_ALPHA = 0.5
DEFAULT_TRAJECTORY_PLOT_PHASE_ALPHA = 0.6
DEFAULT_TRAJECTORY_PLOT_GRID_ALPHA = 0.3
DEFAULT_TRAJECTORY_PLOT_LEGEND_COLUMNS = 3
DEFAULT_TRAJECTORY_PLOT_LEGEND_FONTSIZE = 8
DEFAULT_TRAJECTORY_PLOT_LABEL_FONTSIZE = 9
DEFAULT_TRAJECTORY_PLOT_LABEL_BBOX = {
    "boxstyle": "round,pad=0.2",
    "fc": "white",
    "ec": "none",
    "alpha": 0.6,
}

# Measured in Isaac Sim: T_panda_link7_lacrosse for
# parent=/World/LMM/Franka/panda_link7, child=/World/LMM/Franka/lacrosse.
# USD/Gf.Matrix4d uses row-vector convention, so translation is in row 3.
LINK7_TO_LACROSSE_TRANSLATION = np.array([0.7360306803, 0.002443020341, 0.6644668793], dtype=float)
LINK7_TO_LACROSSE_MATRIX = np.array([
    [5.434818563e-04, -8.201869125e-04, -1.786642114e-04, 0.0],
    [-8.201869008e-04, -5.641629611e-04, 9.493998644e-05, 0.0],
    [-1.786642649e-04, 9.493988578e-05, -9.793188952e-04, 0.0],
    [7.360306803e-01, 2.443020341e-03, 6.644668793e-01, 1.0],
], dtype=float)
